---
- src: ome.omero_common
- src: ome.omego
- src: ome.basedeps
- src: ome.java
- src: ome.omero_python_deps
- src: ome.ice
# https://github.com/ome/ansible-role-postgresql/pull/19
- name: ome.postgresql
  src: >-
    https://github.com/ome/ansible-role-postgresql/archive/8ac895573cbcbbc52b3c397b62b1f1092dcba0cc.tar.gz
